services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
    volumes:
      - hello_world_pgdata:/var/lib/postgresql/data

volumes:
  hello_world_pgdata:
